// <auto-generated />
namespace cryptoGamblers.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class testifresultisreturnedtoopponents : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testifresultisreturnedtoopponents));
        
        string IMigrationMetadata.Id
        {
            get { return "201712141235238_test if result is returned to opponents"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
