// <auto-generated />
namespace cryptoGamblers.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class matchdataaddedtomatch : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(matchdataaddedtomatch));
        
        string IMigrationMetadata.Id
        {
            get { return "201712121300540_matchdata added to match"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
