// <auto-generated />
namespace cryptoGamblers.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class replacedboolaccpetedwithenumaccepted : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(replacedboolaccpetedwithenumaccepted));
        
        string IMigrationMetadata.Id
        {
            get { return "201712121354205_replaced bool accpeted with enum accepted"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
